app/models/tax_svc.rb
solidus_avatax_certified.gemspec

Last year Avatax went down on Black Friday. This caused a lot of
customers to have long checkout times due to the timeouts coming
from Avalara. Lowering the standard read timeout of the restclient
and adding open timeouts will ensure that connections have time
to be established but if there are problems the customer won't
suffer too much.

Added timeouts to all http calls

---

app/models/solidus_avatax_certified/response/address_validation.rb
app/models/solidus_avatax_certified/response/base.rb
app/models/solidus_avatax_certified/response/cancel_tax.rb
app/models/solidus_avatax_certified/response/get_tax.rb
app/models/spree/avalara_transaction.rb
app/models/tax_svc.rb
spec/factories/response_hash_factories.rb
spec/features/checkout_spec.rb
spec/models/solidus_avatax_certified/address_spec.rb
spec/models/solidus_avatax_certified/line_spec.rb
spec/models/solidus_avatax_certified/response/base_spec.rb
spec/models/spree/avalara_transaction_spec.rb
spec/models/spree/calculator/avalara_transaction_spec.rb
spec/models/spree/payment_decorator_spec.rb
spec/models/tax_svc_spec.rb
spec/vcr/address_validation_failure.yml
spec/vcr/address_validation_success.yml
spec/vcr/order_capture.yml
spec/vcr/order_capture_finalize.yml

Clean up how we handle responses.
After this is merged in my next steps are:
1. Request model
2. Improve error handling
3. SOAP API
@dhonig

Response model

---

app/models/spree/avalara_transaction.rb

Fixes an issue with dependency loading that would cause apps to crash with `superclass mismatch for Order`. There is no need for `require_dependency` there as far as I can see, so we can safely remove it.

Fix 'superclass mismatch for Order'

---

app/models/solidus_avatax_certified/line.rb
app/models/solidus_avatax_certified/request/get_tax.rb

Fixes a couple of issues with discount calculation:
* Positive manual adjustments on the order would be considered as discounts when calculating sales tax
* Manual adjustments on the order would not be taken into consideration when setting the `discounted` property for line items

Discount bugfixes

---

app/decorators/models/solidus_avatax_certified/spree/line_item_decorator.rb
app/decorators/models/solidus_avatax_certified/spree/order_decorator.rb
app/decorators/models/solidus_avatax_certified/spree/payment_decorator.rb
app/decorators/models/solidus_avatax_certified/spree/refund_decorator.rb

Uniformize decorators' module names and fix a few typos.

Fix typos in some decorators module names

---

Gemfile

The Solidus branch was hardcoded to 'master'. No matter what branch was
specified on CI build matrix, it was always testing against Solidus' master branch.

Evaluate specific solidus branches in CI

---

solidus_avatax_certified.gemspec

This PR is going to require deface >= 1.5
`frozen_string_literal: true` in [/app/overrides](https://github.com/boomerdigital/solidus_avatax_certified/blob/master/app/overrides/spree/admin/shared/_configuration_menu.rb#L1) requires deface `~> 1.5`
ref https://github.com/spree/deface/pull/182

Require deface 1.5

---

db/seeds.rb
lib/solidus_avatax_certified/preference_seeder.rb
lib/tasks/load_seeds.rake

Since the preferences aren't persisted to DB anymore, the `PreferenceSeeder.seed!` method was only (re)setting the preferences to their default values.
This deprecates it and removes the `solidus_avatax_certified:load_preferences` rake task.
To avoid breaking existing apps that somehow uses `PreferenceSeeder.seed!`, I preferred to not completely remove it. Instead, if called, it shows now a deprecation message and resets the Avatax preferences to their default values.
(a separate PR deprecating/removing also the `PreferenceUpdater` related logic will follow)
Ref issue: #133
TODO:

Deprecate preference seeder

---

lib/solidus_avatax_certified/seeder.rb

Before this PR the task
`bundle exec rake solidus_avatax_certified:load_seeds`
failed with:
```
rake aborted!
NameError: uninitialized constant SolidusAvataxCertified::Spree::AvalaraEntityUseCode
./bin/bundle:3:in `load'
./bin/bundle:3:in `<main>'
Caused by:
NameError: uninitialized constant SolidusAvataxCertified::Spree::AvalaraEntityUseCode
./bin/bundle:3:in `load'
./bin/bundle:3:in `<main>'
Tasks: TOP => solidus_avatax_certified:load_seeds
(See full trace by running task with --trace)
```
This PR fixes it.

Fix Spree::Entities load

---

spec/models/tax_svc_spec.rb

Using raise_error without passing an exception class or message is dangerous because it effectively swallows all errors, making the test pass. Instead, we should listen for the specific exception we expect the code to raise.

Fix usage of raise_error without an exception class

---

CHANGELOG.md
solidus_avatax_certified.gemspec

We're moving to github_changelog_generator for all Solidus extensions due to its ease of use.

Use github_changelog_generator for changelog

---

README.md

These are currently in the wiki, but they are outdated and the readme is usually the right place for this kind of stuff. This is in line with documentation improvements we're doing for other extensions.

Move installation and setup instructions to the readme

---

config/routes.rb

When adding `avalara_information` routes for admin/users don't (re)create the default CRUD routes for users.
These routes are placed on the top of the routes table (hence a higher priority) and might cause unexpected conflicts with other routes definitions.

Don't redefine admin/users default CRUD routes

---

README.md

This corrects the broken link at the beginning of the README which points to the Avalara Certified Page.

Fix broken README link to Avalara Certified Page

---

app/models/solidus_avatax_certified/line.rb

In reference to issue: https://github.com/boomerdigital/solidus_avatax_certified/issues/127

Truncate itemCode

---

app/models/spree/avatax_configuration.rb

Since the changes that were made in [this](https://github.com/solidusio/solidus/pull/4064) PR, it was deprecated to use instance methods in the preferences.
In order to make this work as expected, we have added the code into a class method which will be called in the instance method.

Make default_environment a class method

---

app/decorators/models/solidus_avatax_certified/spree/shipping_rate_decorator.rb

The Spree.t method was deprecated in Solidus 2.8 [1], and was removed in Solidus 3.0.
1: https://github.com/solidusio/solidus/pull/2915/commits/fc0cdb457be5c5dd65656e708d54a329fb43984e

Replace Spree.t method removed in Solidus 3.0

---

Gemfile
app/models/spree/avatax_configuration.rb

The arity of a proc given as the default for a preference has changed from 0 to 1 on Solidus 3.1. The Solidus version for the loaded preference defaults is given as the proc's argument from this point on.
So we need to change the proc so that it doesn't have lambda semantics (lambdas raise when extra arguments are supplied, while raw procs don't).
Ref: https://github.com/solidusio/solidus/blob/b855247cdd32b556f64552e9933a7c7bb091cda5/core/lib/spree/preferences/preferable_class_methods.rb#L36

Update configuration to use proc

---

Gemfile

Starting from 15 March 2022 it's not possible anymore to connect to GitHub using SSH keys [1] so we need to use https instead.
1: https://github.blog/2021-09-01-improving-git-protocol-security-github/

Fix connection to GitHub over SSH

---

lib/solidus_avatax_certified/testing_support/factories.rb

We copied the tests for some models in our project because we wanted to decorate some of them. But running the tests raises an error for a missing factory. We tried to load the factories from the gem but adding require 'solidus_avatax_certified/testing_support/factories' in the rails_helper raises this error:
FactoryBot::DuplicateDefinitionError:
Sequence already registered: SKU
This happens because the line require 'spree/testing_support/factories' in the gem factories tries to load Solidus factories, but they're already loaded.
Since that requirement is useless, we can safely remove it.

Remove useless requirements from factories
